### ISSUE TITLE
Add Support for background: true Option in mongo_index Resource

### ISSUE THREAD

**Issue by arsensimonyanpicsart** [KIABI-OSS/terraform-provider-mongodb#6]
**Background:**
Currently, when using the `mongo_index` resource in the Terraform provider for MongoDB to create an index, there's no option to specify `background: true`. This is crucial because without the `background` option set to `true`, MongoDB will lock the collection during the index creation process. This lock can cause significant downtime, as it prevents write operations on the affected collection until the index creation completes. In production environments, this can be highly undesirable and may lead to service disruptions.

**Proposal:**
I propose adding support for the `background: true` option in the `mongo_index` resource. This option will allow index creation to occur in the background, without locking the database and interrupting write operations. With this enhancement, users can ensure uninterrupted service while still maintaining index functionality.

**Comment by Joe-Woodhead-BigChange** [comment]
@arsensimonyanpicsart I'm not well versed in Go or Terraform but have got a PR for adding this functionality below:

https://github.com/KIABI-OSS/terraform-provider-mongodb/pull/7

We also required this functionality.

**Comment by AdrienBennadji** [comment]
Hello,

Thank you @arsensimonyanpicsart for opening the issue and @Joe-Woodhead-BigChange for the PR. I'll review, merge it and push a new release this week. Sorry for the delay.

**Comment by AdrienBennadji** [comment]
The PR has been merged but note that this won't do anything for mongo versions >= 4.2 : https://www.mongodb.com/docs/v5.3/reference/method/db.collection.createIndex/#options
